Palgrave comms corrections
Nikoleta-v3/bibliometric-study-of-the-prisoners-dilemma pull request #103
Opened 2020-11-30 11:51 UTC by Nikoleta-v3

This is my go at correcting the manuscript for resubmission at Palgrave communications. 

There are a few TODOs left in the `main.tex`. That is because there are specific things I would like you to look over @drvinceknight.

A list of things left to do (more for myself):

- [ ] prepare notebooks and repo for publication
- [ ] write a draft response to the reviewers
- [ ] (a maybe) prepare any extra material that might be needed for the appendix (for example the analysis with the weighted network)

2020-12-04 11:02 UTC, drvinceknight commented on assets/tex/data_collection_diagram.tex
> +\end{document}
Fair play @Nikoleta-v3 this is a lovely diagram.

2020-12-04 13:26 UTC, drvinceknight requested changes
I believe there's still the one `TODO` that I have not addressed. I will get to it.

Looks great though @Nikoleta-v3, thanks for all your work.

2020-12-04 13:26 UTC, drvinceknight commented on assets/tex/data_collection_diagram.tex
> +-6.5) {\textbf{FIND} semantic similar titles \textbf{REMOVE} duplicate articles};
```suggestion
-6.5) {\textbf{FIND} semantically similar titles \textbf{REMOVE} duplicate articles};
```

2020-12-04 13:26 UTC, drvinceknight commented on assets/tex/data_collection_diagram.tex
> +
```suggestion
\node [place, draw=orange!80, fill=orange!25, font=\footnotesize, text width=14em, text badly centered] (authors) at (5,
-8.5) {\textbf{FIND} semantically similar authors \\ \textbf{FIX} author
names in all entries to have the same convention};

```

2020-12-04 13:26 UTC, drvinceknight commented on assets/tex/data_collection_diagram.tex
> +\node (title) at (1.5, 1.2) {COLLECTING DATA FROM SOURCES};
```suggestion
\node (title) at (1.5, 1.2) {DATA COLLECTING};
```

I don't feel strongly about this, just to make it match the other "titles" although ADDITIONS could also possibly be "SUPPLEMENTING"

2020-12-04 13:26 UTC, drvinceknight commented on main.tex
> +
```suggestion
\title{A bibliometric study of research topics, collaboration and centrality 
       in the Iterated Prisoner's Dilemma}
```

I think it's nice to include the centrality in there as a way of "replacing" influence. **But** I also like what you had before.

2020-12-04 13:26 UTC, drvinceknight commented on main.tex
>  network suggests that authors are focused on their communities and not many
```suggestion
network suggests that authors are focused on their communities and that not many
```

2020-12-04 13:26 UTC, drvinceknight commented on main.tex
> +because papers that have not been published yet can be collected. The search
```suggestion
they are well known publishers in the field, and the arXiv preprint server. 
The search
```

2020-12-04 13:26 UTC, drvinceknight commented on main.tex
> +the papers included in the analysis are relevant. Moreover, an amount of well
How correct is this sentence @Nikoleta-v3 ? It makes it sound like all articles were manually checked...

2020-12-04 13:26 UTC, drvinceknight commented on main.tex
> +
```suggestion
```

:+1:

2020-12-04 13:26 UTC, drvinceknight commented on main.tex
> +\item prisoner game theory
```suggestion
    \item prisoner's dilemma
    \item prisoners dilemma
    \item prisoner dilemma
    \item prisoners evolution
    \item prisoner game theory
```

😆 (Sorry)

2020-12-04 13:26 UTC, drvinceknight commented on main.tex
> +terms that have been used, for example ``donation game''. The authors believe
```suggestion
terms that could have been used, for example ``donation game''. The authors believe
```

2020-12-04 13:26 UTC, drvinceknight commented on main.tex
> +existed within the title, the abstract or the text are included in the analysis.
text? 

Is it not just the abstract?

2020-12-04 13:26 UTC, drvinceknight commented on main.tex
> +reverence over time are presented in Section~\ref{subsection:research_topics}.
```suggestion
relevance over time are presented in Section~\ref{subsection:research_topics}.
```

2020-12-04 13:26 UTC, drvinceknight commented on main.tex
> +into research topics using LDA an unsupervised machine learning technique
```suggestion
into research topics using LDA, an unsupervised machine learning technique
```

2020-12-04 13:26 UTC, drvinceknight commented on main.tex
> +contribution denoted as \(c\). For example the words and their associated
```suggestion
each document by the probabilities of belonging to a specific topic. The
probability of a document belonging to topic \(T\) is referred to as the percentage
contribution denoted as \(c_T\). For example the words and their associated
```

2020-12-04 13:26 UTC, drvinceknight commented on main.tex
> +coherence score~\cite{Roder2015} and the exclusivity~\cite{Airoldi2012}. The
```suggestion
the algorithm. The appropriate number of topics can be chosen based on the
coherence score~\cite{Roder2015} or the exclusivity score~\cite{Airoldi2012}. The
```

2020-12-04 13:26 UTC, drvinceknight commented on main.tex
> +The topic coherence for each model was calculated using the
```suggestion
exclusivity of 18 models where the number of topics \(n \in \{2, 3, \dots, 18\}\).
The topic coherence for each model was calculated using the
```

2020-12-04 13:26 UTC, drvinceknight commented on main.tex
> +
```suggestion
the number of topics with the highest coherence score are \(n=6\) (coherence score
of 0.418) and \(n=12\) (coherence score of 0.417).
Figure~\ref{fig:coherence_value_over_number_of_topics} shows that the
exclusivity of the highly weighted words of the topics is decreasing as the number
of topics increases. When \(n=5\) the exclusivity value is better
than for the model of \(n=6\), and its coherence score is 0.406 (which is close to
0.418). For that reason \(n=5\) is chosen to carry out the analysis of this work.

```

2020-12-04 13:26 UTC, drvinceknight commented on main.tex
> +
We could include a scatter plot of exclusivity vs coherence, this would essentially show us the "pareto front" and could be a nice way to illustrate what you're saying there.

2020-12-04 13:26 UTC, drvinceknight commented on main.tex
> +sets. The performance of the models is then compared based on:
```suggestion
sets. The performance of the models are then compared based on:
```

2020-12-04 13:26 UTC, drvinceknight commented on main.tex
> +Moreover, there are less good than the models of periods 1951-1965 to 1951-1995.
```suggestion
Moreover, these are less good than the models of periods 1951-1965 to 1951-1995.
```

2020-12-04 13:26 UTC, drvinceknight commented on main.tex
> +however are small. The relevances of the five topics has been increasing
```suggestion
however is small. The relevances of the five topics has been increasing
```

2020-12-04 13:26 UTC, drvinceknight commented on main.tex
> +The collaborativeness of the authors is analysed using measures such as, isolated nodes,
```suggestion
The collaborativeness of the authors is analysed using measures such as, number of isolated nodes,
```

2020-12-04 13:26 UTC, drvinceknight commented on main.tex
> +connected components, clustering coefficient, communities, modularity and average degree.
```suggestion
number of connected components, clustering coefficient, number of communities, modularity and average degree.
```

2020-12-04 13:26 UTC, drvinceknight commented on main.tex
> +an author to contact others, and betweenness centrality is a
```suggestion
an author to reachothers, and betweenness centrality is a
```

2020-12-04 13:26 UTC, drvinceknight commented on main.tex
> +measure of how many paths pass through a specific node. All centrality measure can
```suggestion
measure of how many paths pass through a specific node. All centrality measures 
```

2020-12-04 13:26 UTC, drvinceknight commented on main.tex
> +topics' networks are very low  except from the case of Topic D. From the
```suggestion
topics' networks are low except from the case of Topic D. From the
```

2020-12-04 13:26 UTC, drvinceknight commented on main.tex
> +modeling problems as a PD. These 5 topics nicely summarise the PD research. They
```suggestion
modeling problems as a PD. These 5 topics nicely summarise PD research. They
```

2020-12-04 13:26 UTC, drvinceknight commented on main.tex
> +over the course of time, and it revealed that even though there were not
```suggestion
over the course of time, and it revealed that even though they were not
```

2020-12-04 13:26 UTC, drvinceknight commented on main.tex
> +network. It was concluded that the field is a collaborative field, where authors
```suggestion
Section~\ref{subsection:co_authorship} investigated the co-authorship
network. It was concluded that the field is a collaborative field, where authors
```

2020-12-04 13:26 UTC, drvinceknight commented on main.tex
> +theoretic fields, and it was shown that the PD network is more collaborative. The
```suggestion
theoretic fields, and it was shown that the PD network is relatively more collaborative. The
```

2020-12-04 13:26 UTC, drvinceknight commented on main.tex
> +    number of topics here were chosen only based on the coherence score.
```suggestion
    1951-2018. The number of topics \(n\) for each period is given in the column
    ``Topic". For example in the period 1951-1980 the selected \(n\) was 13. The
    number of topics here were chosen only based on the coherence score.
```

2020-12-04 14:42 UTC, Nikoleta-v3 commented on main.tex
> +the papers included in the analysis are relevant. Moreover, an amount of well
Yeah this is not accurate. This needs to change

2020-12-04 14:42 UTC, Nikoleta-v3 commented on main.tex
> +existed within the title, the abstract or the text are included in the analysis.
No it is the text as well. That is why the reviewers questioned if all the articles are relevant

2020-12-04 14:44 UTC, Nikoleta-v3 commented on main.tex
> +an author to contact others, and betweenness centrality is a
`reach others`

2020-12-04 15:39 UTC, drvinceknight commented on main.tex
> +existed within the title, the abstract or the text are included in the analysis.
But that's not always the case right? Or is it? Did all the APIs give the article text? For some reason I thought it was just the title and the abstract...

2020-12-04 15:46 UTC, drvinceknight commented on main.tex
> +existed within the title, the abstract or the text are included in the analysis.
I understand now, thanks for clarifying my misunderstanding on slack. :+1:

2020-12-07 13:03 UTC, drvinceknight requested changes

2020-12-07 13:03 UTC, drvinceknight commented on main.tex
> +%TODO me trying to sound poetic/publishable. Feel free to delete.
```suggestion
```

2020-12-07 13:03 UTC, drvinceknight commented on main.tex
> +collaboration of authors in a single topic.
```suggestion
connections across the communities are made. The most central authors of the network
are the authors connected to the main cluster. Through examining the networks
of topics, it was uncovered that the main cluster is characterised by the
collaboration of authors in a single topic.

These findings add to the bibliometrics study in another field and present new questions 
and avenues of research to understand the reasons for the measured behaviours.
```

2020-12-15 17:10 UTC, merged